language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master